name: Deploy Function main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN_PROD }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID_PROD }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
          
      - run: supabase link --project-ref $PROJECT_ID
      - run: supabase functions deploy --no-verify-jwt